# 🦎 Komodo
# ---

services:
  mongo:
    image: mongo:8.2.9
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
      - komodo-internal-network
    # ports:
    #   - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_db_user:/run/secrets/komodo_db_username:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_db_pass:/run/secrets/komodo_db_password:ro
    env_file: ${COMPOSE_PROJECT_DIR}/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/komodo_db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/komodo_db_password
    deploy:
      resources:
        limits:
          memory: 2g
  
  core:
    image: ghcr.io/moghtech/komodo-core:1.19.5
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    networks:
      caddy-proxy:
          aliases:
            - komodo
      komodo-internal-network: {}
    depends_on:
      - mongo
    env_file: ${COMPOSE_PROJECT_DIR}/.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME_FILE: /run/secrets/komodo_db_username
      KOMODO_DATABASE_PASSWORD_FILE: /run/secrets/komodo_db_password
      KOMODO_INIT_ADMIN_USERNAME_FILE: /run/secrets/komodo_admin_username
      KOMODO_INIT_ADMIN_PASSWORD_FILE: /run/secrets/komodo_admin_password
      KOMODO_PASSKEY_FILE: /run/secrets/komodo_passkey
      KOMODO_WEBHOOK_SECRET_FILE: /run/secrets/komodo_webhook_secret
      KOMODO_JWT_SECRET_FILE: /run/secrets/komodo_jwt_secret
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_db_user:/run/secrets/komodo_db_username:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_db_pass:/run/secrets/komodo_db_password:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_admin_user:/run/secrets/komodo_admin_username:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_admin_pass:/run/secrets/komodo_admin_password:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_passkey:/run/secrets/komodo_passkey:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_webhook_secret:/run/secrets/komodo_webhook_secret:ro
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_jwt_secret:/run/secrets/komodo_jwt_secret:ro
    deploy:
      resources:
        limits:
          memory: 2g
          
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    networks:
      - komodo-internal-network
    env_file: ${COMPOSE_PROJECT_DIR}/.env
    environment:
      PERIPHERY_PASSKEYS_FILE: /run/secrets/komodo_passkey
    volumes:
      # ✅ Map the **rootless** Podman socket:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock

      ## Allow Periphery to see processes outside of container
      - /proc:/proc:ro
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY}:${PERIPHERY_ROOT_DIRECTORY}:Z
      - ${COMPOSE_PROJECT_DIR}/.secrets/komodo_passkey:/run/secrets/komodo_passkey:ro
    deploy:
      resources:
        limits:
          memory: 2g

networks:
  caddy-proxy:
    external: true

  komodo-internal-network:
    name: komodo-internal-network
    driver: bridge

volumes:
  # Mongo
  mongo-data:
  mongo-config: