services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.0
    env_file: .env
    volumes:
      - ./config:/app/config
    networks:
      caddy-proxy:
        aliases:
          - homepage

networks:
  caddy-proxy:
    external: true
