---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Homebase:
  - Komodo:
      icon: komodo
      href: http://komodo.home.arpa
      description: Homelab Container Management

      widgets:
        - type: komodo
          url: http://komodo:9120
          key: {{HOMEPAGE_VAR_KOMODO_KEY}}
          secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
          showSummary: true 
          showStacks: true 

  - AdGuard Home:
      icon: adguard-home
      href: http://adguard.home.arpa
      description: Network-wide DNS & ad blocking

      widgets:
        - type: adguard
          url: http://adguard.home.arpa
          username: {{HOMEPAGE_VAR_ADGUARD_USER}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASS}}
