services:
  adguard-home:
    image: adguard/adguardhome:latest
    command:
      - '--no-check-update'
      - '-c'
      - /opt/adguardhome/conf/AdGuardHome.yaml
      - '-w'
      - /opt/adguardhome/work
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    # ONLY DNS ports should be exposed
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      caddy-proxy:
        aliases:
          - adguard-home
  
networks:
  caddy-proxy:
    external: true
